### PR TITLE
archlinux: use dracut native file instead of our own

### PR DESCRIPTION
**Pull request by ptitdoc**

### CODE REVIEW

**Comment by marmarek** [comment]
Could you sign this?

**Comment by ptitdoc** [comment]
I quite sure I signed a commit tag.

**Comment by ptitdoc** [comment]
Hum tags are not pushed automatically :)

**Comment by ptitdoc** [comment]
Is it good with the signed tag, or do I need to create a new pull request ?

**Comment by marmarek** [comment]
> Is it good with the signed tag, or do I need to create a new pull request ?

It's ok now :)

**Pull request merged**
