### PR TITLE
Archlinux: Fix booting TemplateVMs using pvgrub

### PR DESCRIPTION
**Pull request by ptitdoc**

### CODE REVIEW

**Comment by marmarek** [comment]
Is it possible to reuse existing dracut/initramfs scripts? Like including them in initramfs, then calling in `run_earlyhook`.
And, please sign your code.

**Comment by ptitdoc** [comment]
That is probably possible, but it looks dangerous:
- Initramfs also needs to be configured to load specific binaries or scripts in case of changes
- Calling functions from external scripts can be easily broken especially by race conditions bugs if scripts with the same functions names are loaded before.

**Comment by ptitdoc** [comment]
As it is already a standalone script, it is probably feasible. Should I use the full-dmroot script ?
https://github.com/marmarek/qubes-linux-utils/blob/master/dracut/full-dmroot/qubes_cow_setup.sh

Sorry for not signing the code, I just activated automatic signature yesterday when seing the github failure.

**Comment by marmarek** [comment]
> As it is already a standalone script, it is probably feasible. Should I use the full-dmroot script ?

Yes, this one is the "primary" one.

**Comment by marmarek** [comment]
If it needs some minor Archlinux-specific modifications, it's ok - see for example how logging is handled (which is different in Debian vs Fedora).

**Comment by ptitdoc** [comment]
OK, I will test that later (hopefully this week).

**Comment by ptitdoc** [comment]
Replaced with https://github.com/marmarek/qubes-linux-utils/pull/9

**Pull request closed without merging**
